<%if !empty($head.webspeed.alog)%>
	<script>void function(g,f,j,c,h,d,b){g.alogObjectName=h,g[h]=g[h]||function(){(g[h].q=g[h].q||[]).push(arguments)},g[h].l=g[h].l||+new Date,d=f.createElement(j),d.async=!0,d.src=c,b=f.getElementsByTagName(j)[0],b.parentNode.insertBefore(d,b)}(window,document,"script",__uri("/static/alog.min.js"),"alog");void function(){function c(){return}window.PDC={mark:function(a,b){alog("speed.set",a,b||+new Date);alog.fire&&alog.fire("mark")},init:function(a){alog("speed.set","options",a)},view_start:c,tti:c,page_ready:c}}();void function(n){var o=!1;n.onerror=function(n,e,t,c){var i=!0;return !e&&/^script error/i.test(n)&&(o?i=!1:o=!0),i&&alog("exception.send","exception",{msg:n,js:e,ln:t,col:c}),!1},alog("exception.on","catch",function(n){alog("exception.send","exception",{msg:n.msg,js:n.path,ln:n.ln,method:n.method,flag:"catch"})})}(window);</script>
<%else%>
	<%if $sysInfo.country != 'tw' && $sysInfo.country != 'sa'%>
	<script>(function(){window.PDC={_timing:{},_opt:{sample:0.01},_analyzer:{loaded:false,url:__uri("/static/js/wpo.pda.js"),callbacks:[]},_render_start:+new Date,extend:function(b,a){for(property in b){a[property]=b[property]}return a},metadata:function(){var c=this._opt;var e={env:{user:(c.is_login==true?1:0),product_id:c.product_id,page_id:PDC._is_sample(c.sample)?c.page_id:0},render_start:this._render_start,timing:this._timing};var a=[];var d=c.special_pages||[];for(var b=0;b<d.length;b++){if(PDC._is_sample(d[b]["sample"])){a.push(d[b]["id"])}}if(a.length>0){e.env["special_id"]="["+a.join(",")+"]"}return e},init:function(a){this.extend(a,this._opt)},mark:function(a,b){this._timing[a]=b||+new Date},view_start:function(){this.mark("vt")},tti:function(){this.mark("tti")},page_ready:function(){this.mark("fvt")},first_screen:function(){var g=document.getElementsByTagName("img"),a=+new Date;var f=[],e=this;function b(h){var j=0;j=window.pageYOffset?window.pageYOffset:document.documentElement.scrollTop;try{j+=h.getBoundingClientRect().top}catch(i){}finally{return j}}this._setFS=function(){var k=e._opt["fsHeight"]||document.documentElement.clientHeight;for(var j=0;j<f.length;j++){var l=f[j],h=l.img,n=l.time,m=b(h);if(m>0&&m<k){a=n>a?n:a}}e._timing.fs=a};var d=function(){if(this.removeEventListener){this.removeEventListener("load",d,false)}f.push({img:this,time:+new Date})};for(var c=0;c<g.length;c++){(function(){var h=g[c];if(h.addEventListener){!h.complete&&h.addEventListener("load",d,false)}else{if(h.attachEvent){h.attachEvent("onreadystatechange",function(){if(h.readyState=="complete"){d.call(h,d)}})}}})()}}};if(document.attachEvent){window.attachEvent("onload",function(){PDC.mark("let");PDC._setFS&&PDC._setFS();PDC._opt.ready!==false&&PDC._load_analyzer()})}else{window.addEventListener("load",function(){PDC.mark("lt")},false)}})();</script> 
	<%else%>
	<script>(function(){window.__wpo={};__wpo.util={extend:function(c,b){for(var a in b){c[a]=b[a]}return c},now:function(){return +new Date}};__wpo.pdc={_description:"based on perf api",_version:"0.8",_support_perf_api:false,_time_to_title:__wpo.util.now(),_render_start:-1,_analyzer:{url:__uri("/static/js/wpo.timing.pda.hao123.js")},_opt:{sample:0,product_id:0,page_id:0,is_login:false,net_test:{sample:1,url:""},log_path:"http://static.tieba.baidu.com/tb/pms/img/st.gif"},_timing:{},_random:-1,init:function(a){if(window.performance&&window.performance.timing){this._support_perf_api=true;this._render_start=window.performance.timing.navigationStart}__wpo.util.extend(this._opt,a)},mark:function(b){this._timing[b]=__wpo.util.now()},_is_sample:function(a){if(this._random<0){this._random=Math.random()}return this._support_perf_api&&(this._random<=a)}};PDC=__wpo.pdc})();</script>
	<%/if%>
<%/if%>
