== FIS3

=== FIS3 进度
. 2015-05-15
+
总体进度 95%
.. 单测 / 测试 *90%*

. 2015-05-08 进度
+
总体进度 *90%*

.. Review *85%*
... 注释补充
... 提供对本地插件挂载的支持
.. 单测 / 测试 *70%*
... 性能测试 *0%*
.. 文档 *60%*
.. Demo *20%*
... basic 体验 FIS 诸多编译功能
... full 包含组件化、合并等较全功能

. 2015-04-30 进度
+
总体进度 *75%*

.. Review *60%*
... 修改若干接口
.... 异构语言内嵌只对.html文件支持，后端模板不予支持
... 给同名依赖加上开关
... 插件 Global 可访问到 Local 的插件
+
考虑到 FIS3 安装一遍压力山大
+
代码版本管理问题
+
代码拆分问题

... AMD 内置，用户可配置就能用了
+
----
AMD 处理原则

1. 用户开发，设定组件目录，下面的所有组件都不可自己写 `define`，由工具编译添加。
2. 如果对于需要分享出去的组件，可以写没有 moduleId 的 `define`
3. 使用第三方 AMD 组件，只要运行时 loader 支持就行

- 为什么需要加 moduleId ？

    合并的需要

- 为什么有 1 这样的一个开发方式而不是要求用户去写？

    要满足合并的需要，还是要加 moduleId 的，那么对于已经添加 define 的组件，编译工具需要 AST 分析，耗时大概是正则的 6-7 倍，这是一件很蛋碎的事情。

- 如果没有第 3 条，那么实现一个简单的 loader 就可以了，只需要把异步组件的静态资源映射表输出到页面，供 loader 查询。这样的好处是，整个 loader 很简短 ，大概 200 行内就能搞定了，不再需要加载一个偌大的 2k 左右的包到页面上。

----

.. 单测 *60%*，覆盖率达到 60%
.. 文档 *0%*
.. 测试 *0%*
... 功能完整性
... 性能
... 已经和测试沟通，下周开始投入测试中，包括补充单测。

. 2015-04-23 进度
+
总体进度 *65%* 正式发布时间预计延期 *2* 周

.. 完成功能开发
.. 调整参数细节，Review *40%*
.. 实现单测 *20%*
.. 文档进度 *0%*
.. 测试 *0%*

IMPORTANT: *Review* 环节非常重要，可能会邀请非组织内人员进行 *Review*

=== FIS3 功能点

. 人性化的配置 API
.. fis.match
.. fis.plugin
.. fis.media
. 可自定义三种语言能力接口(语法)
. 支持内嵌异构语言脚本
. 支持按需编译
. 兼容现有社区插件
. lint 过程调整到编译最前面
. 去除 test 插件扩展点
. 产出相对路径支持
. 打包策略调整
.. 支持分包功能
. 支持 FIS 安装到*本地*
. 默认产出 ID 调整
.. JS 不再带有扩展名，方便 AMD 这种规范能轻松接入 (*非常艰难的决定*)
. https://github.com/fis-components[组件 repos] 支持
. https://github.com/fis-scaffold[脚手架体系]
. 工程化社区 (延后)

=== FIS3 FIS2 功能对照表

[cols="1,1a,1a" options="header"]
.配置
|===
|
| FIS2
| FIS3

| 配置插件
|
[source,javascript]
----
fis.config.set('modules', ...)
fis.config.set('settings', ...)
----
|
[source,javascript]
----
fis.plugin('plugin-name', {
  /*settings*/
})
----

| roadmap.path
|
[source,javascript]
----
fis.config.set('roadmap.path', [
    {
        reg: '**.js'
        , ...
    }
])
----
|
[source,javascript]
----
fis.match('**js', {
})
----


| roadmap.domain
|
[source,javascript]
----
fis.config.set('roadmap.domain', ...)
----
|
[source,javascript]
----
fis.match('**.js', {
    domain: 'http://cdn.baidu.com/',
    ...
})
----

| roadmap.ext
|
[source,javascript]
----
fis.config.set('roadmap.ext',
    {less:
        'css'
    })
----
|
[source,javascript]
----
fis.match('**.less', {
    rExt: 'css',
    ...
})
----

| pack
|
[source,javascript]
----
fis.config.set('pack', {
    'all.js': '**.js'
})
----
|
[source,javascript]
----
fis.match('**.js', {
    packTo: 'all.js'
})
----

| deploy
|
[source,javascript]
----
fis.config.set('deplay.rd', {
    ...
})
----
|
[source,javascript]
----
fis.media('rd').set('deploy', {
    ...
})
fis.media.match('**', {
    deploy: fis.media('dev').get('deploy')
})
----

|===


[cols="1,1a" options="header"]
.命令行 (release)
|===
| FIS2
| FIS3

| -c, --clean
| -c, --clean

| -w, --watch
| -w, --watch

| -L, --live
| -L, --live

| -u, --unique
| -u, --unique

| -r, --root
| -r, --root

| -d, --dest <names> //@TODO
| -d, --dest <names> //@TODO

| -h, --help
| -h, --help

| -f, --file <filename>
| -f, --file

| -l, --lint
| file.useLint

| -D, --domains
| file.domain; fis.useDomain

| -t, --test
| file.useTest

| -o, --optimize
| file.useOptimize

| -m, --md5
| file.useHash; file.keepOrigin
|===

[cols='1,1a,1a,1a' options="header"]
.File
|===
|
| FIS2
| FIS3
| 说明

| 表现形式
| fis.config.set('roadmap.path', []);
| 文件属性
|

| roadmap
| reg
| *
|

|
| release
| release
|

|
| url
| url
|

|
| query
| query
|

|
| id
| id
|

|
| charset
| charset
|

|
| isHtmlLike
| isHtmlLike
|

|
| isCssLike
| isCssLike
|

|
| isJsLike
| isJsLike
|

|
| useCompile
| useCompile
| 默认*关*还是*开*，需要讨论

|
| useHash
| useHash
| 保留原文件路径这个需要再确认下？

|
| useDomain
| domain: ''
| 如果设置了就加，不设置就不加了。

|
| useCache
| useCache
| *默认都有*

|
| useMap
| useMap
| js,css 默认入表，FIS2, FIS3无差别

|
| useParser
| parser: fis.plugin(...)
| 如果设置了插件就执行，没有设置就不过这类插件？

|
| usePreprocessor
| preprocessor: fis.plugin(...)
| 同上

|
| useStandard
| standard: fis.plugin(...)
| 同上；这块需要*注意*，当未配置 standard 插件的时候，会调用 builtin 进行类 FIS2
的 三种语言语法 分析，但 js 中的 *require* 移交给插件去分析处理，因为各种规范下写法
 有点异样；
IMPORTANT: js require 不再 builtin 处理
|
| usePostprocessor
| postprocessor: fis.plugin(...)
| 同上

|
| useLint
| lint: fis.plugin(...)
| 同上

|
| useOptimizer
| optimizer: fis.plugin(...)
| 同上

|
| useTest
| <DEL>
| 不再在编译流程需要这个了

|
| useSprite
| sprite: fis.plugin(...)
| 同上的上

|
| isMod
| isMod
|

|
| extras
| extras
|

|
| requires
| requires
|

|===

## FIS3

### File 对象

[cols="1,1a,1a" options="header"]
.File
|===
| class
| 默认属性
| 后缀

| Base
| ----
ext
rExt
realpath
realpathNoExt

subpath
subdirname
subpathNoExt

release
url

charset
id
----
|

| All
| ----
useCompile = true;
useDomain = false;
useCache = true;
useHash = false;
useMap = false;
_isImage = true;
_isText = false;
----
| `.[\w]`

| isHtmlLike
| ----
useHash = false
useDomain = false
_isText = true
----
| ....
.html
.xhtml
.shtml
.htm
.tpl
.ftl
.vm
.php
.jsp
.asp
.aspx
.ascx
.cshtml
.master
....

| isCssLike
| ----
useHash = true
useDomain = false
_isText = true
useMap = true
----
| ....
.css
.scss
.sass
.less
.styl
....

| isJsLike
| ----
useHash = true
useDomain = true
_isText = true
useMap = true
----
| ....
.js
.jsx
.coffee
....

| isJsonLike
|
| ....
.json
....

| isImage
| ----
useDomain = true
useHash = true // exclude '.ico'
|

----

|===


### 内嵌异构语言脚本

[source,html]
.index.html
----
...
<script type="text/x-coffee">
    //...
</script>
...
----

[source,html]
.index.html
----
<style type="text/x-less">
body {
    background-color: #F0F0F0;
    h1 {
        color: red;
    }
}
</style>
----
